services:
  mongod:
    image: mongodb/mongodb-community-server:8.2-ubuntu2204-slim
    command: mongod --replSet rs0
    ports:
      - 27017:27017

  mongot:
    image: mongodb/mongodb-community-search:latest
    ports:
      - 27028:27028
    depends_on:
      - mongod
