services:
  mongodb:
    image: mongodb/mongodb-atlas-local
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=mongo
      - MONGODB_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    hostname: mongodb
    deploy:
      resources:
        limits:
          memory: 8G